version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Git..."
      - apt-get update && apt-get install -y git

  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone https://github.com/viraj-wagh/CI-CD-Pipeline-Project.git
      - cd CI-CD-Pipeline-Project
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - cd ..

  build:
    commands:
      - echo "Building Docker image..."
      - cd CI-CD-Pipeline-Project
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-project:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-project:latest"
      - cd ..

  post_build:
    commands:
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: CI-CD-Pipeline-Project
